# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e94927e441a831142af82c24fda2c2633e24c928c48e4ad9ae7d13e094e7af208ca5ac1cf61789dcf77de83a4655a03c2dc926796dcdc3134045f844e9ec19d1
  mail_username: jimmyyang5296@gmail.com
  mail_password: a04mr9e6nq


test:
  secret_key_base: 7cff745ae7166c88200f9e66d165bfa2cd3053d45bf0e14bb5031a073e9bee629c1524d1125e8835a188d67a6cce138e94447ecd7c995cc412769cf8426f881c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
